# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0002_auto_20151230_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='drip',
            name='body_plain_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
