# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0004_drip_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='If true, this drip will be disabled immediately after it is sent to all applicable users.'),
        ),
    ]
